// Code generated by Slice Machine. DO NOT EDIT.

import Accordeon from './Accordeon/index.svelte';
import BoxCenter from './BoxCenter/index.svelte';
import BoxDouble from './BoxDouble/index.svelte';
import BoxSingle from './BoxSingle/index.svelte';
import BoxTripple from './BoxTripple/index.svelte';
import Cards from './Cards/index.svelte';
import Chapter from './Chapter/index.svelte';
import Chat from './Chat/index.svelte';
import Cloud from './Cloud/index.svelte';
import DogBreak from './DogBreak/index.svelte';
import Expertise from './Expertise/index.svelte';
import Headline from './Headline/index.svelte';
import Image from './Image/index.svelte';
import List from './List/index.svelte';
import Logos from './Logos/index.svelte';
import Newsletter from './Newsletter/index.svelte';
import Opener1 from './Opener1/index.svelte';
import Opener2 from './Opener2/index.svelte';
import Slider from './Slider/index.svelte';
import Text from './Text/index.svelte';
import TextBig from './TextBig/index.svelte';
import Video from './Video/index.svelte';
import VideoGallery from './VideoGallery/index.svelte';
import Welcome from './Welcome/index.svelte';
import Work from './Work/index.svelte';

export const components = {
	accordeon: Accordeon,
	box_center: BoxCenter,
	box_double: BoxDouble,
	box_single: BoxSingle,
	box_tripple: BoxTripple,
	cards: Cards,
	chapter: Chapter,
	chat: Chat,
	cloud: Cloud,
	dog_break: DogBreak,
	expertise: Expertise,
	headline: Headline,
	image: Image,
	list: List,
	logos: Logos,
	newsletter: Newsletter,
	opener1: Opener1,
	opener2: Opener2,
	slider: Slider,
	text: Text,
	text_big: TextBig,
	video: Video,
	video_gallery: VideoGallery,
	welcome: Welcome,
	work: Work
};
