// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Navigation Bottom → Navigation*
 */
export interface NavigationBottomDocumentDataNavigationItem {
	/**
	 * Text field in *Navigation Bottom → Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_bottom.navigation[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * Link field in *Navigation Bottom → Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_bottom.navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for Navigation Bottom documents
 */
interface NavigationBottomDocumentData {
	/**
	 * Navigation field in *Navigation Bottom*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_bottom.navigation[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navigation: prismic.GroupField<Simplify<NavigationBottomDocumentDataNavigationItem>>;
}

/**
 * Navigation Bottom document from Prismic
 *
 * - **API ID**: `navigation_bottom`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationBottomDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<NavigationBottomDocumentData>,
		'navigation_bottom',
		Lang
	>;

/**
 * Item in *Navigation Top → Navigation*
 */
export interface NavigationTopDocumentDataNavigationItem {
	/**
	 * Text field in *Navigation Top → Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_top.navigation[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * Link field in *Navigation Top → Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_top.navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for Navigation Top documents
 */
interface NavigationTopDocumentData {
	/**
	 * Navigation field in *Navigation Top*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_top.navigation[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navigation: prismic.GroupField<Simplify<NavigationTopDocumentDataNavigationItem>>;
}

/**
 * Navigation Top document from Prismic
 *
 * - **API ID**: `navigation_top`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationTopDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavigationTopDocumentData>,
	'navigation_top',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| StickyNavigationSlice
	| VideoGallerySlice
	| WelcomeSlice
	| VideoSlice
	| WorkSlice
	| SliderSlice
	| CloudSlice
	| ImageSlice
	| Opener1Slice
	| CardsSlice
	| Opener2Slice
	| BoxTrippleSlice
	| TextSlice
	| TextBigSlice
	| ListSlice
	| NewsletterSlice
	| LogosSlice
	| DogBreakSlice
	| HeadlineSlice
	| ExpertiseSlice
	| ChapterSlice
	| ChatSlice
	| BoxDoubleSlice
	| BoxSingleSlice
	| BoxCenterSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Background field in *Page*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Light Gray
	 * - **API ID Path**: page.background
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	background: prismic.SelectField<
		'Light Gray' | 'Light Green' | 'Dark gray' | 'Dark Green' | 'Black' | 'White',
		'filled'
	>;

	/**
	 * Logo Color field in *Page*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Light Gray
	 * - **API ID Path**: page.logoColor
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	logoColor: prismic.SelectField<
		'Light Gray' | 'Light Green' | 'Dark gray' | 'Dark Green' | 'Black' | 'White',
		'filled'
	>;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Item in *Work → Items*
 */
export interface WorkDocumentDataItemsItem {
	/**
	 * slide_time field in *Work → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.items[].slide_time
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	slide_time: prismic.NumberField;

	/**
	 * Text field in *Work → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Image field in *Work → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video Url field in *Work → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.items[].video_url
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video_url: prismic.KeyTextField;

	/**
	 * Video Poster field in *Work → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.items[].video_poster
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	video_poster: prismic.ImageField<never>;
}

type WorkDocumentDataSlicesSlice =
	| VideoGallerySlice
	| BoxSingleSlice
	| ChapterSlice
	| ChatSlice
	| BoxDoubleSlice
	| DogBreakSlice
	| HeadlineSlice
	| ExpertiseSlice
	| ListSlice
	| TextSlice
	| NewsletterSlice
	| LogosSlice
	| BoxTrippleSlice
	| TextBigSlice
	| Opener1Slice
	| CardsSlice
	| Opener2Slice
	| SliderSlice
	| CloudSlice
	| ImageSlice
	| WelcomeSlice
	| VideoSlice
	| WorkSlice
	| BoxCenterSlice;

/**
 * Content for Work documents
 */
interface WorkDocumentData {
	/**
	 * Slide Time field in *Work*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.slide_time
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	slide_time: prismic.NumberField;

	/**
	 * clickable field in *Work*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: work.clickable
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	clickable: prismic.BooleanField;

	/**
	 * Title field in *Work*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Client field in *Work*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.client
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	client: prismic.TitleField;

	/**
	 * Related Visible field in *Work*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: work.related_visible
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	related_visible: prismic.BooleanField;

	/**
	 * Related Work 1 field in *Work*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.related_work_1
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	related_work_1: prismic.ContentRelationshipField<'work'>;

	/**
	 * Related Work 2 field in *Work*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.related_work_2
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	related_work_2: prismic.ContentRelationshipField<'work'>;

	/**
	 * Background field in *Work*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Light Gray
	 * - **API ID Path**: work.background
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	background: prismic.SelectField<
		'Light Gray' | 'Light Green' | 'Dark gray' | 'Dark Green' | 'Black' | 'White',
		'filled'
	>;

	/**
	 * Logo Color field in *Work*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Light Gray
	 * - **API ID Path**: work.logoColor
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	logoColor: prismic.SelectField<
		'Light Gray' | 'Light Green' | 'Dark gray' | 'Dark Green' | 'Black' | 'White',
		'filled'
	>;

	/**
	 * Items field in *Work*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.items[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<WorkDocumentDataItemsItem>>;

	/**
	 * Slice Zone field in *Work*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<WorkDocumentDataSlicesSlice> /**
	 * Meta Title field in *Work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: work.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: work.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Work*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<WorkDocumentData>,
	'work',
	Lang
>;

export type AllDocumentTypes =
	| NavigationBottomDocument
	| NavigationTopDocument
	| PageDocument
	| WorkDocument;

/**
 * Primary content in *BoxCenter → Default → Primary*
 */
export interface BoxCenterSliceDefaultPrimary {
	/**
	 * Distance Top field in *BoxCenter → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: box_center.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *BoxCenter → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: box_center.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Text field in *BoxCenter → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_center.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Emoji field in *BoxCenter → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_center.default.primary.emoji
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	emoji: prismic.KeyTextField;

	/**
	 * Color field in *BoxCenter → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: box_center.default.primary.color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color: prismic.SelectField<
		'White' | 'Gray Light' | 'Dark Gray' | 'Green Light' | 'Dark Green' | 'Black',
		'filled'
	>;
}

/**
 * Default variation for BoxCenter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoxCenterSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BoxCenterSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BoxCenter*
 */
type BoxCenterSliceVariation = BoxCenterSliceDefault;

/**
 * BoxCenter Shared Slice
 *
 * - **API ID**: `box_center`
 * - **Description**: BoxCenter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoxCenterSlice = prismic.SharedSlice<'box_center', BoxCenterSliceVariation>;

/**
 * Primary content in *BoxDouble → Default → Primary*
 */
export interface BoxDoubleSliceDefaultPrimary {
	/**
	 * Distance Top field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: box_double.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: box_double.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Color Left field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: box_double.default.primary.color_left
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color_left: prismic.SelectField<
		'White' | 'Light Gray' | 'Dark Gray' | 'Black' | 'Light Green' | 'Green',
		'filled'
	>;

	/**
	 * Image Left field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_double.default.primary.image_left
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_left: prismic.ImageField<never>;

	/**
	 * Headline Left  field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_double.default.primary.headline_left
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline_left: prismic.KeyTextField;

	/**
	 * Text Left  field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_double.default.primary.text_left
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text_left: prismic.RichTextField;

	/**
	 * Color Right field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: box_double.default.primary.color_right
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color_right: prismic.SelectField<
		'White' | 'Light Gray' | 'Dark Gray' | 'Black' | 'Light Green' | 'Green',
		'filled'
	>;

	/**
	 * Image Right field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_double.default.primary.image_right
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_right: prismic.ImageField<never>;

	/**
	 * Headline Right  field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_double.default.primary.headline_right
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline_right: prismic.KeyTextField;

	/**
	 * Text Right field in *BoxDouble → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_double.default.primary.text_right
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text_right: prismic.RichTextField;
}

/**
 * Default variation for BoxDouble Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoxDoubleSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BoxDoubleSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BoxDouble*
 */
type BoxDoubleSliceVariation = BoxDoubleSliceDefault;

/**
 * BoxDouble Shared Slice
 *
 * - **API ID**: `box_double`
 * - **Description**: BoxDouble
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoxDoubleSlice = prismic.SharedSlice<'box_double', BoxDoubleSliceVariation>;

/**
 * Primary content in *BoxSingle → Default → Primary*
 */
export interface BoxSingleSliceDefaultPrimary {
	/**
	 * Distance Top field in *BoxSingle → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: box_single.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *BoxSingle → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: box_single.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Color field in *BoxSingle → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: box_single.default.primary.color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color: prismic.SelectField<
		'White' | 'Light Gray' | 'Dark Gray' | 'Black' | 'Light Green' | 'Green',
		'filled'
	>;

	/**
	 * Headline field in *BoxSingle → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_single.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Number field in *BoxSingle → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_single.default.primary.number
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	number: prismic.NumberField;

	/**
	 * Text field in *BoxSingle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_single.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for BoxSingle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoxSingleSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BoxSingleSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BoxSingle*
 */
type BoxSingleSliceVariation = BoxSingleSliceDefault;

/**
 * BoxSingle Shared Slice
 *
 * - **API ID**: `box_single`
 * - **Description**: BoxSingle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoxSingleSlice = prismic.SharedSlice<'box_single', BoxSingleSliceVariation>;

/**
 * Primary content in *BoxTripple → Default → Primary*
 */
export interface BoxTrippleSliceDefaultPrimary {
	/**
	 * Distance Top field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: box_tripple.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: box_tripple.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Color 1 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: box_tripple.default.primary.color_1
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color_1: prismic.SelectField<
		'White' | 'Light Gray' | 'Dark Gray' | 'Black' | 'Light Green' | 'Green',
		'filled'
	>;

	/**
	 * Image 1 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_tripple.default.primary.image_1
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_1: prismic.ImageField<never>;

	/**
	 * Headline 1 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_tripple.default.primary.headline_1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline_1: prismic.KeyTextField;

	/**
	 * Text 1 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_tripple.default.primary.text_1
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text_1: prismic.RichTextField;

	/**
	 * Color 2 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: box_tripple.default.primary.color_2
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color_2: prismic.SelectField<
		'White' | 'Light Gray' | 'Dark Gray' | 'Black' | 'Light Green' | 'Green',
		'filled'
	>;

	/**
	 * Image 2 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_tripple.default.primary.image_2
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_2: prismic.ImageField<never>;

	/**
	 * Headline 2 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_tripple.default.primary.headline_2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline_2: prismic.KeyTextField;

	/**
	 * Text 2 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_tripple.default.primary.text_2
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text_2: prismic.RichTextField;

	/**
	 * Color 3 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: box_tripple.default.primary.color_3
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color_3: prismic.SelectField<
		'White' | 'Light Gray' | 'Dark Gray' | 'Black' | 'Light Green' | 'Green',
		'filled'
	>;

	/**
	 * Image 3 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_tripple.default.primary.image_3
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_3: prismic.ImageField<never>;

	/**
	 * Headline 3 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_tripple.default.primary.headline_3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline_3: prismic.KeyTextField;

	/**
	 * Text 3 field in *BoxTripple → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: box_tripple.default.primary.text_3
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text_3: prismic.RichTextField;
}

/**
 * Default variation for BoxTripple Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoxTrippleSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BoxTrippleSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BoxTripple*
 */
type BoxTrippleSliceVariation = BoxTrippleSliceDefault;

/**
 * BoxTripple Shared Slice
 *
 * - **API ID**: `box_tripple`
 * - **Description**: BoxTripple
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoxTrippleSlice = prismic.SharedSlice<'box_tripple', BoxTrippleSliceVariation>;

/**
 * Item in *Cards → Default → Primary → Items*
 */
export interface CardsSliceDefaultPrimaryItemsItem {
	/**
	 * Color field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: cards.default.primary.items[].color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color: prismic.SelectField<
		'White' | 'Light Gray' | 'Dark Gray' | 'Black' | 'Light Green' | 'Green',
		'filled'
	>;

	/**
	 * Image field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video Url field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].video_url
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video_url: prismic.KeyTextField;

	/**
	 * Video Poster field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].video_poster
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	video_poster: prismic.ImageField<never>;

	/**
	 * Autoplay field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cards.default.primary.items[].autoplay
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	autoplay: prismic.BooleanField;

	/**
	 * Headline field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Number field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].number
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	number: prismic.NumberField;

	/**
	 * Text field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
	/**
	 * Distance Top field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: cards.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: cards.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Style field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: left_big
	 * - **API ID Path**: cards.default.primary.direction
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	direction: prismic.SelectField<
		'left_big' | 'left_small' | 'center_big' | 'center_small' | 'right_big' | 'right_small',
		'filled'
	>;

	/**
	 * Order Top Bottom field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: cards.default.primary.order_top_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	order_top_bottom: prismic.BooleanField;

	/**
	 * Stacking Top Bottom field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: cards.default.primary.stacking_top_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	stacking_top_bottom: prismic.BooleanField;

	/**
	 * Height field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: s
	 * - **API ID Path**: cards.default.primary.height
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	height: prismic.SelectField<'s' | 'm' | 'l' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Items field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<CardsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice<'cards', CardsSliceVariation>;

/**
 * Primary content in *Chapter → Default → Primary*
 */
export interface ChapterSliceDefaultPrimary {
	/**
	 * Distance Top field in *Chapter → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: chapter.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Chapter → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: chapter.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Color field in *Chapter → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: White
	 * - **API ID Path**: chapter.default.primary.color
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	color: prismic.SelectField<
		'White' | 'Gray Light' | 'Dark Gray' | 'Green Light' | 'Green' | 'Black',
		'filled'
	>;

	/**
	 * Text field in *Chapter → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: chapter.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;
}

/**
 * Default variation for Chapter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChapterSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ChapterSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Chapter*
 */
type ChapterSliceVariation = ChapterSliceDefault;

/**
 * Chapter Shared Slice
 *
 * - **API ID**: `chapter`
 * - **Description**: Chapter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChapterSlice = prismic.SharedSlice<'chapter', ChapterSliceVariation>;

/**
 * Item in *Chat → Default → Primary → Items*
 */
export interface ChatSliceDefaultPrimaryItemsItem {
	/**
	 * Text field in *Chat → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: chat.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Primary content in *Chat → Default → Primary*
 */
export interface ChatSliceDefaultPrimary {
	/**
	 * Distance Top field in *Chat → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: chat.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Chat → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: chat.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Items field in *Chat → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: chat.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<ChatSliceDefaultPrimaryItemsItem>>;

	/**
	 * Text Bottom field in *Chat → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: chat.default.primary.text_bottom
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text_bottom: prismic.RichTextField;

	/**
	 * Emoji field in *Chat → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: chat.default.primary.emoji
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	emoji: prismic.KeyTextField;
}

/**
 * Default variation for Chat Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChatSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ChatSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Chat*
 */
type ChatSliceVariation = ChatSliceDefault;

/**
 * Chat Shared Slice
 *
 * - **API ID**: `chat`
 * - **Description**: Chat
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChatSlice = prismic.SharedSlice<'chat', ChatSliceVariation>;

/**
 * Item in *Cloud → Default → Primary → Items*
 */
export interface CloudSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Cloud → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cloud.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *Cloud → Default → Primary*
 */
export interface CloudSliceDefaultPrimary {
	/**
	 * Distance Top field in *Cloud → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: cloud.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Cloud → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: cloud.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Items field in *Cloud → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cloud.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<CloudSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Cloud Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CloudSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CloudSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Cloud*
 */
type CloudSliceVariation = CloudSliceDefault;

/**
 * Cloud Shared Slice
 *
 * - **API ID**: `cloud`
 * - **Description**: Cloud
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CloudSlice = prismic.SharedSlice<'cloud', CloudSliceVariation>;

/**
 * Primary content in *DogBreak → Default → Primary*
 */
export interface DogBreakSliceDefaultPrimary {
	/**
	 * Distance Top field in *DogBreak → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: dog_break.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *DogBreak → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: dog_break.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Text field in *DogBreak → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: dog_break.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for DogBreak Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DogBreakSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<DogBreakSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *DogBreak*
 */
type DogBreakSliceVariation = DogBreakSliceDefault;

/**
 * DogBreak Shared Slice
 *
 * - **API ID**: `dog_break`
 * - **Description**: DogBreak
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DogBreakSlice = prismic.SharedSlice<'dog_break', DogBreakSliceVariation>;

/**
 * Item in *Expertise → Default → Primary → Items*
 */
export interface ExpertiseSliceDefaultPrimaryItemsItem {
	/**
	 * Headline field in *Expertise → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertise.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Expertise → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertise.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Primary content in *Expertise → Default → Primary*
 */
export interface ExpertiseSliceDefaultPrimary {
	/**
	 * Distance Top field in *Expertise → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: expertise.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Expertise → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: expertise.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Items field in *Expertise → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertise.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<ExpertiseSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Expertise Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExpertiseSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ExpertiseSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Expertise*
 */
type ExpertiseSliceVariation = ExpertiseSliceDefault;

/**
 * Expertise Shared Slice
 *
 * - **API ID**: `expertise`
 * - **Description**: Expertise
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExpertiseSlice = prismic.SharedSlice<'expertise', ExpertiseSliceVariation>;

/**
 * Primary content in *Headline → Default → Primary*
 */
export interface HeadlineSliceDefaultPrimary {
	/**
	 * Distance Top field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: headline.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: headline.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Text 1 field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline.default.primary.text_1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text_1: prismic.KeyTextField;

	/**
	 * Text 2 field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline.default.primary.text_2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text_2: prismic.KeyTextField;

	/**
	 * Style field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: horizontal
	 * - **API ID Path**: headline.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'horizontal' | 'vertical', 'filled'>;
}

/**
 * Default variation for Headline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeadlineSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Headline*
 */
type HeadlineSliceVariation = HeadlineSliceDefault;

/**
 * Headline Shared Slice
 *
 * - **API ID**: `headline`
 * - **Description**: Headline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSlice = prismic.SharedSlice<'headline', HeadlineSliceVariation>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
	/**
	 * Distance Top field in *Image → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: image.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Image → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: image.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Image field in *Image → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Caption field in *Image → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.default.primary.caption
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	caption: prismic.RichTextField;

	/**
	 * Style field in *Image → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Inline
	 * - **API ID Path**: image.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'Inline' | 'Full Rounded' | 'Full Screen', 'filled'>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>;

/**
 * Item in *List → Default → Primary → Items*
 */
export interface ListSliceDefaultPrimaryItemsItem {
	/**
	 * Headline field in *List → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: list.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *List → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: list.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Primary content in *List → Default → Primary*
 */
export interface ListSliceDefaultPrimary {
	/**
	 * Distance Top field in *List → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: list.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *List → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: list.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Items field in *List → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: list.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<ListSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for List Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ListSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *List*
 */
type ListSliceVariation = ListSliceDefault;

/**
 * List Shared Slice
 *
 * - **API ID**: `list`
 * - **Description**: List
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSlice = prismic.SharedSlice<'list', ListSliceVariation>;

/**
 * Item in *Logos → Default → Primary → Items*
 */
export interface LogosSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Logos → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Logo field in *Logos → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.items[].logo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Logos → Default → Primary*
 */
export interface LogosSliceDefaultPrimary {
	/**
	 * Distance Top field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: logos.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: logos.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Items field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<LogosSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Logos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LogosSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Logos*
 */
type LogosSliceVariation = LogosSliceDefault;

/**
 * Logos Shared Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Logos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSlice = prismic.SharedSlice<'logos', LogosSliceVariation>;

/**
 * Primary content in *Newsletter → Default → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
	/**
	 * Distance Top field in *Newsletter → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: newsletter.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Newsletter → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: newsletter.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Headline field in *Newsletter → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Newsletter → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsletter.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NewsletterSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSliceVariation = NewsletterSliceDefault;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSlice = prismic.SharedSlice<'newsletter', NewsletterSliceVariation>;

/**
 * Primary content in *Opener1 → Default → Primary*
 */
export interface Opener1SliceDefaultPrimary {
	/**
	 * Distance Top field in *Opener1 → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: opener1.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Opener1 → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: opener1.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Headline field in *Opener1 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: opener1.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Opener1 → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: opener1.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Image field in *Opener1 → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: opener1.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Opener1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Opener1SliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<Opener1SliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Opener1*
 */
type Opener1SliceVariation = Opener1SliceDefault;

/**
 * Opener1 Shared Slice
 *
 * - **API ID**: `opener1`
 * - **Description**: Opener1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Opener1Slice = prismic.SharedSlice<'opener1', Opener1SliceVariation>;

/**
 * Primary content in *Opener2 → Default → Primary*
 */
export interface Opener2SliceDefaultPrimary {
	/**
	 * Distance Top field in *Opener2 → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: opener2.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Opener2 → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: opener2.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Headline field in *Opener2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: opener2.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Image field in *Opener2 → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: opener2.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Opener2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Opener2SliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<Opener2SliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Opener2*
 */
type Opener2SliceVariation = Opener2SliceDefault;

/**
 * Opener2 Shared Slice
 *
 * - **API ID**: `opener2`
 * - **Description**: Opener2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Opener2Slice = prismic.SharedSlice<'opener2', Opener2SliceVariation>;

/**
 * Item in *Slider → Default → Primary → Items*
 */
export interface SliderSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Slider → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: slider.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Autoplay field in *Slider → Default → Primary → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: slider.default.primary.items[].autoplay
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	autoplay: prismic.BooleanField;

	/**
	 * Video Url field in *Slider → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: slider.default.primary.items[].video_url
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video_url: prismic.KeyTextField;

	/**
	 * Video Poster field in *Slider → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: slider.default.primary.items[].video_poster
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	video_poster: prismic.ImageField<never>;
}

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
	/**
	 * Distance Top field in *Slider → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: slider.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Slider → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: slider.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Items field in *Slider → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: slider.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<SliderSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SliderSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<'slider', SliderSliceVariation>;

/**
 * Item in *StickyNavigation → Default → Primary → items*
 */
export interface StickyNavigationSliceDefaultPrimaryItemsItem {
	/**
	 * Text field in *StickyNavigation → Default → Primary → items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sticky_navigation.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * Link field in *StickyNavigation → Default → Primary → items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sticky_navigation.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *StickyNavigation → Default → Primary*
 */
export interface StickyNavigationSliceDefaultPrimary {
	/**
	 * Logo Color field in *StickyNavigation → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Light Gray
	 * - **API ID Path**: sticky_navigation.default.primary.logoColor
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	logoColor: prismic.SelectField<
		'Light Gray' | 'Light Green' | 'Dark gray' | 'Dark Green' | 'Black' | 'White',
		'filled'
	>;

	/**
	 * items field in *StickyNavigation → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sticky_navigation.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<StickyNavigationSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for StickyNavigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StickyNavigationSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<StickyNavigationSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *StickyNavigation*
 */
type StickyNavigationSliceVariation = StickyNavigationSliceDefault;

/**
 * StickyNavigation Shared Slice
 *
 * - **API ID**: `sticky_navigation`
 * - **Description**: StickyNavigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StickyNavigationSlice = prismic.SharedSlice<
	'sticky_navigation',
	StickyNavigationSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
	/**
	 * Distance Top field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: text.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: text.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Text field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Style field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Inline
	 * - **API ID Path**: text.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'Inline' | 'Full', 'filled'>;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<'text', TextSliceVariation>;

/**
 * Primary content in *TextBig → Default → Primary*
 */
export interface TextBigSliceDefaultPrimary {
	/**
	 * Distance Top field in *TextBig → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: text_big.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *TextBig → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: text_big.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Text field in *TextBig → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_big.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Style field in *TextBig → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Left
	 * - **API ID Path**: text_big.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'Left' | 'Center' | 'Right' | 'Inline', 'filled'>;
}

/**
 * Default variation for TextBig Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBigSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextBigSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextBig*
 */
type TextBigSliceVariation = TextBigSliceDefault;

/**
 * TextBig Shared Slice
 *
 * - **API ID**: `text_big`
 * - **Description**: TextBig
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBigSlice = prismic.SharedSlice<'text_big', TextBigSliceVariation>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
	/**
	 * Distance Top field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: video.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: video.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Autoplay field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: video.default.primary.autoplay
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	autoplay: prismic.BooleanField;

	/**
	 * Video Url field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video.default.primary.video_url
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video_url: prismic.KeyTextField;

	/**
	 * Video Poster field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video.default.primary.video_poster
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	video_poster: prismic.ImageField<never>;

	/**
	 * Style field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Inline
	 * - **API ID Path**: video.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'Inline' | 'Full Rounded' | 'Full Screen', 'filled'>;

	/**
	 * Caption field in *Video → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video.default.primary.caption
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	caption: prismic.RichTextField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<VideoSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<'video', VideoSliceVariation>;

/**
 * Item in *VideoGallery → Default → Primary → Items*
 */
export interface VideoGallerySliceDefaultPrimaryItemsItem {
	/**
	 * Autoplay field in *VideoGallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: video_gallery.default.primary.items[].autoplay
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	autoplay: prismic.BooleanField;

	/**
	 * Video Url field in *VideoGallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_gallery.default.primary.items[].video_url
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video_url: prismic.KeyTextField;

	/**
	 * Video Poster field in *VideoGallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_gallery.default.primary.items[].video_poster
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	video_poster: prismic.ImageField<never>;
}

/**
 * Primary content in *VideoGallery → Default → Primary*
 */
export interface VideoGallerySliceDefaultPrimary {
	/**
	 * Distance Top field in *VideoGallery → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: video_gallery.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *VideoGallery → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: video_gallery.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Items field in *VideoGallery → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: video_gallery.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<VideoGallerySliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for VideoGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoGallerySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<VideoGallerySliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *VideoGallery*
 */
type VideoGallerySliceVariation = VideoGallerySliceDefault;

/**
 * VideoGallery Shared Slice
 *
 * - **API ID**: `video_gallery`
 * - **Description**: VideoGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoGallerySlice = prismic.SharedSlice<'video_gallery', VideoGallerySliceVariation>;

/**
 * Item in *Welcome → Default → Primary → Items*
 */
export interface WelcomeSliceDefaultPrimaryItemsItem {
	/**
	 * Project field in *Welcome → Default → Primary → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: welcome.default.primary.items[].project
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	project: prismic.ContentRelationshipField<'work'>;
}

/**
 * Primary content in *Welcome → Default → Primary*
 */
export interface WelcomeSliceDefaultPrimary {
	/**
	 * Items field in *Welcome → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: welcome.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<WelcomeSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Welcome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<WelcomeSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Welcome*
 */
type WelcomeSliceVariation = WelcomeSliceDefault;

/**
 * Welcome Shared Slice
 *
 * - **API ID**: `welcome`
 * - **Description**: Welcome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeSlice = prismic.SharedSlice<'welcome', WelcomeSliceVariation>;

/**
 * Item in *Work → Default → Primary → Items*
 */
export interface WorkSliceDefaultPrimaryItemsItem {
	/**
	 * Project field in *Work → Default → Primary → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.default.primary.items[].project
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	project: prismic.ContentRelationshipField<'work'>;
}

/**
 * Primary content in *Work → Default → Primary*
 */
export interface WorkSliceDefaultPrimary {
	/**
	 * Distance Top field in *Work → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: work.default.primary.distance_top
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_top: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Distance Bottom field in *Work → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: work.default.primary.distance_bottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	distance_bottom: prismic.SelectField<'none' | 'xs' | 's' | 'm' | 'xl' | 'xxl', 'filled'>;

	/**
	 * Items field in *Work → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<WorkSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Work Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<WorkSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Work*
 */
type WorkSliceVariation = WorkSliceDefault;

/**
 * Work Shared Slice
 *
 * - **API ID**: `work`
 * - **Description**: Work
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSlice = prismic.SharedSlice<'work', WorkSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			NavigationBottomDocument,
			NavigationBottomDocumentData,
			NavigationBottomDocumentDataNavigationItem,
			NavigationTopDocument,
			NavigationTopDocumentData,
			NavigationTopDocumentDataNavigationItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			WorkDocument,
			WorkDocumentData,
			WorkDocumentDataItemsItem,
			WorkDocumentDataSlicesSlice,
			AllDocumentTypes,
			BoxCenterSlice,
			BoxCenterSliceDefaultPrimary,
			BoxCenterSliceVariation,
			BoxCenterSliceDefault,
			BoxDoubleSlice,
			BoxDoubleSliceDefaultPrimary,
			BoxDoubleSliceVariation,
			BoxDoubleSliceDefault,
			BoxSingleSlice,
			BoxSingleSliceDefaultPrimary,
			BoxSingleSliceVariation,
			BoxSingleSliceDefault,
			BoxTrippleSlice,
			BoxTrippleSliceDefaultPrimary,
			BoxTrippleSliceVariation,
			BoxTrippleSliceDefault,
			CardsSlice,
			CardsSliceDefaultPrimaryItemsItem,
			CardsSliceDefaultPrimary,
			CardsSliceVariation,
			CardsSliceDefault,
			ChapterSlice,
			ChapterSliceDefaultPrimary,
			ChapterSliceVariation,
			ChapterSliceDefault,
			ChatSlice,
			ChatSliceDefaultPrimaryItemsItem,
			ChatSliceDefaultPrimary,
			ChatSliceVariation,
			ChatSliceDefault,
			CloudSlice,
			CloudSliceDefaultPrimaryItemsItem,
			CloudSliceDefaultPrimary,
			CloudSliceVariation,
			CloudSliceDefault,
			DogBreakSlice,
			DogBreakSliceDefaultPrimary,
			DogBreakSliceVariation,
			DogBreakSliceDefault,
			ExpertiseSlice,
			ExpertiseSliceDefaultPrimaryItemsItem,
			ExpertiseSliceDefaultPrimary,
			ExpertiseSliceVariation,
			ExpertiseSliceDefault,
			HeadlineSlice,
			HeadlineSliceDefaultPrimary,
			HeadlineSliceVariation,
			HeadlineSliceDefault,
			ImageSlice,
			ImageSliceDefaultPrimary,
			ImageSliceVariation,
			ImageSliceDefault,
			ListSlice,
			ListSliceDefaultPrimaryItemsItem,
			ListSliceDefaultPrimary,
			ListSliceVariation,
			ListSliceDefault,
			LogosSlice,
			LogosSliceDefaultPrimaryItemsItem,
			LogosSliceDefaultPrimary,
			LogosSliceVariation,
			LogosSliceDefault,
			NewsletterSlice,
			NewsletterSliceDefaultPrimary,
			NewsletterSliceVariation,
			NewsletterSliceDefault,
			Opener1Slice,
			Opener1SliceDefaultPrimary,
			Opener1SliceVariation,
			Opener1SliceDefault,
			Opener2Slice,
			Opener2SliceDefaultPrimary,
			Opener2SliceVariation,
			Opener2SliceDefault,
			SliderSlice,
			SliderSliceDefaultPrimaryItemsItem,
			SliderSliceDefaultPrimary,
			SliderSliceVariation,
			SliderSliceDefault,
			StickyNavigationSlice,
			StickyNavigationSliceDefaultPrimaryItemsItem,
			StickyNavigationSliceDefaultPrimary,
			StickyNavigationSliceVariation,
			StickyNavigationSliceDefault,
			TextSlice,
			TextSliceDefaultPrimary,
			TextSliceVariation,
			TextSliceDefault,
			TextBigSlice,
			TextBigSliceDefaultPrimary,
			TextBigSliceVariation,
			TextBigSliceDefault,
			VideoSlice,
			VideoSliceDefaultPrimary,
			VideoSliceVariation,
			VideoSliceDefault,
			VideoGallerySlice,
			VideoGallerySliceDefaultPrimaryItemsItem,
			VideoGallerySliceDefaultPrimary,
			VideoGallerySliceVariation,
			VideoGallerySliceDefault,
			WelcomeSlice,
			WelcomeSliceDefaultPrimaryItemsItem,
			WelcomeSliceDefaultPrimary,
			WelcomeSliceVariation,
			WelcomeSliceDefault,
			WorkSlice,
			WorkSliceDefaultPrimaryItemsItem,
			WorkSliceDefaultPrimary,
			WorkSliceVariation,
			WorkSliceDefault
		};
	}
}
